import img1 from '../../Photos/img1.jpg';
import img2 from '../../Photos/img2.png';
import img3 from '../../Photos/img3.jpg';
import img4 from '../../Photos/img4.jpg';
import img5 from '../../Photos/img5.jpg';
import img6 from '../../Photos/img6.png';
import img7 from '../../Photos/img7.jpg';
import img8 from '../../Photos/img8.png';
import img9 from '../../Photos/img9.png';
import img10 from '../../Photos/img10.jpg';
import img11 from '../../Photos/img11.jpg';
import img12 from '../../Photos/img12.jpg';
import img13 from '../../Photos/img13.jpg';
import img14 from '../../Photos/img14.jpg';
import img15 from '../../Photos/img15.jpg';
import img16 from '../../Photos/img16.jpg';
import img17 from '../../Photos/img17.jpg';
import img18 from '../../Photos/img18.jpg';
import img19 from '../../Photos/img19.jpg';
import img20 from '../../Photos/img20.jpg';

const images=[img1,img2,img3,img4,img5,img6,img7,img8,img9,img10,img11,img12,img13,img14,img15,img16,img17,img18,img19,img20];
export default images;